const translations = {
    pt: {
        nav_services: 'Soluções', nav_cases: 'Cases', nav_about: 'Sobre', nav_contact: 'Contato', nav_lang_btn: 'EN', skip_content: 'Pular para o conteúdo',
        hero_eyebrow: 'SAAS · MOBILE · IA APLICADA · ENGENHARIA SÊNIOR',
        hero_title: 'Seu próximo produto digital, com <em>IA no lugar certo.</em>',
        hero_subtitle: 'Eu desenho e desenvolvo SaaS e apps mobile que transformam uma oportunidade comercial ou operacional em produto pronto para vender, operar e evoluir.',
        hero_cta: '<i class="fab fa-whatsapp" aria-hidden="true"></i><span>Conversar sobre meu produto</span>',
        hero_secondary: 'Ver projetos selecionados', hero_proof: 'SaaS · Mobile · IA aplicada · execução ponta a ponta', hero_status: 'online',
        hero_terminal_result: 'sistema pronto para gerar valor', hero_metric_1_label: 'EXPERIÊNCIA', hero_metric_1_value: 'anos', hero_metric_2_label: 'ESCOPO', hero_metric_2_value: 'ponta a ponta', hero_metric_3_label: 'ATUAÇÃO', hero_metric_3_value: 'remoto', hero_float_1_label: 'foco em', hero_float_1_value: 'resultado', hero_float_2_label: 'engenharia', hero_float_2_value: 'confiável', hero_scroll: 'explorar',
        signal_label: 'ONDE A TECNOLOGIA ENCONTRA O NEGÓCIO', signal_1: 'Produtos web', signal_2: 'Apps Android &amp; iOS', signal_3: 'IA aplicada', signal_4: 'Arquitetura &amp; APIs',
        offer_kicker: 'DUAS FRENTES, UMA VISÃO DE PRODUTO', offer_title: 'Comece pelo produto que move o seu negócio.', offer_intro: 'SaaS é o núcleo para vender e operar em escala. Mobile é a camada que leva esse valor para o cliente ou para a equipe em campo. Em ambos, a IA entra com objetivo, dados e controle.',
        offer_saas_label: '01 / CORE', offer_saas_badge: 'SAAS + IA', offer_saas_title: 'Plataformas SaaS que viram operação.', offer_saas_desc: 'Da proposta de valor ao painel que o time usa todos os dias: produto web, APIs, dados e uma camada de IA que reduz trabalho e melhora decisões.', offer_saas_item_1: 'MVP, portal, dashboard ou produto recorrente', offer_saas_item_2: 'Copilotos, busca inteligente, automações e scoring', offer_saas_item_3: 'Arquitetura pronta para medir, vender e evoluir', offer_saas_result: 'Receba um caminho claro do diagnóstico ao produto em produção.', offer_saas_link: 'Explorar desenvolvimento SaaS',
        offer_mobile_label: '02 / COMPANION', offer_mobile_badge: 'MOBILE + IA', offer_mobile_title: 'Apps que acompanham cada momento.', offer_mobile_desc: 'Experiências Android e iOS para clientes e equipes em campo, conectadas ao SaaS e assistidas por IA quando contexto e velocidade importam.', offer_mobile_item_1: 'Offline, localização, notificações e tempo real', offer_mobile_item_2: 'Assistência contextual para registrar, consultar e agir', offer_mobile_item_3: 'Uma base cross-platform com experiência nativa', offer_mobile_result: 'Receba uma jornada simples para o usuário e confiável para a operação.', offer_mobile_link: 'Explorar apps mobile', offer_foot: 'A IA não é um enfeite: é uma decisão de produto que precisa gerar ganho observável, com segurança e revisão humana quando necessário.', offer_cta: 'Quero mapear uma oportunidade',
        about_visual_label: 'PERFIL / ENGENHARIA &amp; PRODUTO', about_visual_status: 'disponível para novos desafios', about_visual_role: 'Senior Software Engineer', about_visual_focus: 'produto · arquitetura · entrega', about_link_note: 'perfil profissional',
        about_image_caption: 'engenharia com visão de negócio', about_kicker: 'A pessoa por trás do produto', about_title: 'Tecnologia boa é a que deixa o negócio mais forte.',
        about_p1: 'Sou Glauber Barcelos, engenheiro de software sênior. Ao longo de mais de duas décadas, atuei em produtos digitais, saúde, startups, operações críticas e plataformas que precisam funcionar de verdade.',
        about_p2: 'Meu trabalho combina visão de produto, arquitetura, execução hands-on e comunicação clara. Eu entro para organizar o problema, escolher o caminho certo e entregar a solução completa — sem traduzir cada decisão para uma cadeia de fornecedores.',
        about_linkedin: 'Conheça minha trajetória no LinkedIn', about_pillar_1: 'Negócio antes da tecnologia', about_pillar_2: 'Arquitetura que aguenta crescer', about_pillar_3: 'Entrega visível e previsível',
        services_kicker: 'O que eu posso construir com você', services_title: 'Da primeira decisão ao produto em operação.', services_intro: 'Você não precisa comprar “horas de desenvolvimento”. Precisa de uma solução que ajude a vender, operar melhor, validar uma ideia ou escalar com segurança.', services_meta_1: 'anos construindo', services_meta_2: 'visão de produto', services_meta_3: 'linha de execução', services_closer_label: 'DO DESAFIO À ENTREGA', services_closer_text: 'Uma única linha de execução para conectar negócio, tecnologia e resultado.',
        service_web_kicker: 'SaaS / produto principal', service_web_title: 'SaaS que vende e opera', service_web_desc: 'Plataformas, portais, dashboards e jornadas comerciais desenhados para validar a oferta, organizar a operação e escalar com IA aplicada.', service_web_link: 'Conhecer desenvolvimento SaaS',
        service_mobile_kicker: 'Companion / operação', service_mobile_title: 'Apps Android &amp; iOS com IA', service_mobile_desc: 'Aplicativos multiplataforma para clientes e equipes em campo, conectados ao seu produto e com assistência de IA onde a jornada pede velocidade.', service_mobile_link: 'Conhecer desenvolvimento de aplicativos mobile',
        service_ai_kicker: 'Inteligência aplicada', service_ai_title: 'IA aplicada', service_ai_desc: 'Automação, assistentes, busca inteligente e decisões orientadas por dados — IA onde ela gera valor de verdade.', service_ai_link: 'Conversar sobre inteligência artificial aplicada',
        service_arch_kicker: 'Base para crescer', service_arch_title: 'Arquitetura &amp; APIs', service_arch_desc: 'Backend, integrações, observabilidade e performance para produtos que precisam ser confiáveis hoje e amanhã.', service_arch_link: 'Conversar sobre arquitetura e APIs',
        service_advisory_kicker: 'Visão sênior', service_advisory_title: 'Consultoria &amp; liderança técnica', service_advisory_desc: 'Uma visão sênior para tirar decisões do campo das opiniões: diagnóstico, roadmap, priorização, revisão de arquitetura e condução hands-on.', service_advisory_link_page: 'Conhecer consultoria e liderança técnica', service_advisory_link: 'Quero conversar sobre um desafio',
        method_kicker: 'Como o trabalho acontece', method_title: 'Clareza para decidir. Ritmo para entregar.', method_intro: 'A tecnologia entra como instrumento. Primeiro vem o contexto, depois a decisão certa, então a construção e a evolução contínua.', method_cta: 'Começar pelo diagnóstico', method_visual_caption: 'visão de ponta a ponta', method_visual_principle_1: 'problema entendido', method_visual_principle_2: 'decisão registrada', method_visual_principle_3: 'produto em evolução',
        method_1_title: 'Entender', method_1_desc: 'Mapeio o objetivo, os usuários, as restrições e o que realmente precisa mudar.', method_1_tag: 'contexto', method_2_title: 'Desenhar', method_2_desc: 'Transformo o problema em escopo, arquitetura e prioridades que cabem no momento do negócio.', method_2_tag: 'direção', method_3_title: 'Construir', method_3_desc: 'Desenvolvo com entregas visíveis, decisões registradas e qualidade desde a primeira versão.', method_3_tag: 'entrega', method_4_title: 'Evoluir', method_4_desc: 'Acompanho o pós-lançamento, leio os sinais e ajusto o produto para ele continuar gerando valor.', method_4_tag: 'evolução',
        cases_kicker: 'Prova para uma decisão comercial', cases_title: 'Produtos reais, jornadas críticas e páginas que deixam o próximo passo evidente.', cases_intro: 'Veja como SaaS, mobile e IA aplicada entram em contextos de saúde, telecom, franquias e startups sem perder clareza de negócio.', cases_note_label: 'SELEÇÃO CURADA', cases_note_text: 'Produto, operação e conversão na mesma entrega.', case_footer_note: 'do contexto à entrega', case_open_project: 'Ver landing page',
        case_samu_tag: 'SAÚDE · MOBILE', case_samu_outcome: 'Operação crítica em tempo real', case_true_client: 'Projeto realizado para a TRUE Tecnologia para Vida', case_samu_title: 'SAMU 192', case_samu_desc: 'Uma jornada crítica, em que geolocalização, tempo real e simplicidade precisam funcionar quando cada segundo importa. O produto conecta chamada, localização e atendimento em uma experiência simples para quem precisa agir rápido.',
        case_unimed_tag: 'SAÚDE · APP', case_unimed_outcome: 'Jornada digital para beneficiários', case_unimed_title: 'Unimed', case_unimed_desc: 'Experiência digital para beneficiários com cobertura, autorizações e serviços no mesmo lugar. Uma jornada mais clara para acessar informações, serviços e próximos passos sem fricção.',
        case_banana_tag: 'STARTUP · IA', case_banana_outcome: 'Match inteligente para decisão', case_banana_title: 'Banana Startups', case_banana_desc: 'Match inteligente entre startups e investidores: da hipótese ao MVP com base para aprender e crescer. A experiência aproxima descoberta, critérios e conexão em um só fluxo.',
        case_native_tag: 'SAAS · WEB', case_native_outcome: 'SaaS com narrativa de conversão', case_native_title: 'Native IP', case_native_desc: 'Comunicação técnica traduzida em benefícios comerciais para uma plataforma SaaS de provedores de internet. A página transforma uma oferta complexa em uma conversa comercial mais direta.',
        case_streetme_tag: 'FRANQUIA · WEB', case_streetme_outcome: 'Captação para expansão de marca', case_streetme_title: 'StreetMe Cafés', case_streetme_desc: 'Landing page de captação de franqueados com narrativa de negócio, prova de mercado e caminho claro até o lead. Cada bloco foi pensado para reduzir dúvidas e acelerar o próximo contato.',
        case_turquesa_tag: 'FRANQUIA · BELEZA', case_turquesa_outcome: 'Aquisição para uma rede em expansão', case_turquesa_title: 'Turquesa Bem-Estar', case_turquesa_desc: 'Experiência comercial para apresentar o modelo de franquia, organizar indicadores e conduzir o empreendedor até o próximo passo com mais confiança.',
        case_empreender_tag: 'EVENTO · WEB', case_empreender_outcome: 'Experiência digital para conexão e venda', case_empreender_title: 'Empreender 40+', case_empreender_desc: 'Landing page para o Summit Empreender 40+, organizando proposta, palestrantes, programação e conversão de ingressos em uma jornada de evento clara.', case_empreender_link: 'Ver site do projeto',
        fit_kicker: 'Talvez o próximo projeto seja o seu', fit_title: 'Se existe uma oportunidade, um gargalo ou uma ideia importante, dá para começar.', fit_1: 'Você precisa validar um MVP sem montar um time inteiro.', fit_2: 'Seu produto cresceu e a arquitetura começou a cobrar a conta.', fit_3: 'A empresa quer aplicar IA, mas ainda não sabe onde faz sentido.', fit_4: 'Você precisa de alguém sênior para conectar decisão e execução.',
        contact_kicker: 'Próximo passo', contact_title: 'Vamos transformar uma oportunidade em produto.', contact_intro: 'Conte o que você quer vender, operar ou simplificar. Em uma conversa objetiva, organizamos o primeiro recorte e o melhor caminho para SaaS, mobile e IA.', contact_aside_label: 'O QUE VOCÊ RECEBE', contact_aside_text: 'Clareza sobre prioridade, escopo inicial e próximos passos — sem compromisso com um pacote genérico.', contact_context_label: 'O QUE VOCÊ PODE ENVIAR', contact_context_1: 'Um SaaS para validar ou levar à operação', contact_context_2: 'Um app para cliente, equipe ou campo', contact_context_3: 'Uma oportunidade de IA com ganho claro', contact_availability: 'Você fala direto com quem pensa produto, arquitetura e execução — do primeiro recorte à evolução.', contact_whatsapp: '+55 (51) 98012-0387', contact_email: 'ggbarcelos@gmail.com', contact_form_kicker: 'BRIEFING RÁPIDO', contact_form_title: 'Vamos começar pelo contexto certo.', contact_linkedin: 'LinkedIn / glauber-gomes-barcelos', contact_name_label: 'Seu nome', contact_name_ph: 'Como posso te chamar?', contact_wa_label: 'WhatsApp', contact_wa_ph: '(51) 98012-0387', contact_msg_label: 'O que você quer construir?', contact_msg_ph: 'Pode ser uma ideia, um problema ou um projeto em andamento…', contact_submit: '<span>Enviar contexto</span><i class="fas fa-arrow-right" aria-hidden="true"></i>',
        footer_copy: '© 2026 Glauber Barcelos. Engenharia de software para produtos que avançam.', wa_float_label: 'Falar pelo WhatsApp',
        err_name: 'Informe seu nome completo.', err_contact: 'Informe um número de WhatsApp válido, ex: (51) 98012-0387.', err_message: 'Conte um pouco mais sobre o que você quer construir.', err_fields: 'Revise os campos destacados e tente novamente.', sending: 'Enviando mensagem...', sent_ok: 'Mensagem enviada! Vou te chamar no WhatsApp em breve. 🚀', send_error: 'Não foi possível enviar agora. Tente pelo WhatsApp.', send_btn_original: '<span>Enviar contexto</span><i class="fas fa-arrow-right" aria-hidden="true"></i>'
    },
    en: {
        nav_services: 'Solutions', nav_cases: 'Cases', nav_about: 'About', nav_contact: 'Contact', nav_lang_btn: 'PT', skip_content: 'Skip to content',
        hero_eyebrow: 'SAAS · MOBILE · APPLIED AI · SENIOR ENGINEERING',
        hero_title: 'Your next digital product, with <em>AI in the right place.</em>',
        hero_subtitle: 'I design and build SaaS and mobile products that turn a commercial or operational opportunity into something ready to sell, run and evolve.',
        hero_cta: '<i class="fab fa-whatsapp" aria-hidden="true"></i><span>Talk about my product</span>', hero_secondary: 'See selected projects', hero_proof: 'SaaS · Mobile · Applied AI · end-to-end delivery', hero_status: 'online',
        hero_terminal_result: 'system ready to create value', hero_metric_1_label: 'EXPERIENCE', hero_metric_1_value: 'years', hero_metric_2_label: 'SCOPE', hero_metric_2_value: 'end to end', hero_metric_3_label: 'REACH', hero_metric_3_value: 'remote', hero_float_1_label: 'focused on', hero_float_1_value: 'outcomes', hero_float_2_label: 'reliable', hero_float_2_value: 'engineering', hero_scroll: 'explore',
        signal_label: 'WHERE TECHNOLOGY MEETS BUSINESS', signal_1: 'Web products', signal_2: 'Android &amp; iOS apps', signal_3: 'Applied AI', signal_4: 'Architecture &amp; APIs',
        offer_kicker: 'TWO TRACKS, ONE PRODUCT VIEW', offer_title: 'Start with the product that moves your business.', offer_intro: 'SaaS is the core for selling and operating at scale. Mobile is the layer that brings that value to customers or field teams. In both, AI enters with purpose, data and control.',
        offer_saas_label: '01 / CORE', offer_saas_badge: 'SAAS + AI', offer_saas_title: 'SaaS platforms that become operations.', offer_saas_desc: 'From value proposition to the dashboard your team uses every day: web product, APIs, data and an AI layer that removes work and improves decisions.', offer_saas_item_1: 'MVP, portal, dashboard or recurring product', offer_saas_item_2: 'Copilots, intelligent search, automations and scoring', offer_saas_item_3: 'Architecture ready to measure, sell and evolve', offer_saas_result: 'Get a clear path from discovery to a product in production.', offer_saas_link: 'Explore SaaS development',
        offer_mobile_label: '02 / COMPANION', offer_mobile_badge: 'MOBILE + AI', offer_mobile_title: 'Apps that move with every moment.', offer_mobile_desc: 'Android and iOS experiences for customers and field teams, connected to your SaaS and assisted by AI when context and speed matter.', offer_mobile_item_1: 'Offline, location, notifications and real-time flows', offer_mobile_item_2: 'Contextual assistance to record, find and act', offer_mobile_item_3: 'A cross-platform foundation with a native feel', offer_mobile_result: 'Get a simple journey for users and a reliable base for operations.', offer_mobile_link: 'Explore mobile apps', offer_foot: 'AI is not decoration: it is a product decision that must create observable gain, with safety and human review when needed.', offer_cta: 'Map an opportunity',
        about_visual_label: 'PROFILE / ENGINEERING &amp; PRODUCT', about_visual_status: 'available for new challenges', about_visual_role: 'Senior Software Engineer', about_visual_focus: 'product · architecture · delivery', about_link_note: 'professional profile',
        about_image_caption: 'engineering with business vision', about_kicker: 'The person behind the product', about_title: 'Good technology makes the business stronger.',
        about_p1: 'I am Glauber Barcelos, a senior software engineer. Over more than two decades, I have worked on digital products, healthcare, startups, critical operations and platforms that need to work for real.', about_p2: 'My work combines product thinking, architecture, hands-on execution and clear communication. I come in to organize the problem, choose the right path and deliver the complete solution — without turning every decision into a chain of vendors.', about_linkedin: 'See my journey on LinkedIn', about_pillar_1: 'Business before technology', about_pillar_2: 'Architecture built to grow', about_pillar_3: 'Visible, predictable delivery',
        services_kicker: 'What I can build with you', services_title: 'From the first decision to a product in operation.', services_intro: 'You do not need to buy “development hours”. You need a solution that helps you sell, operate better, validate an idea or scale safely.', services_meta_1: 'years building', services_meta_2: 'product vision', services_meta_3: 'execution line', services_closer_label: 'FROM CHALLENGE TO DELIVERY', services_closer_text: 'One execution line connecting business, technology and outcomes.', service_web_kicker: 'SaaS / core product', service_web_title: 'SaaS that sells and runs', service_web_desc: 'Platforms, portals, dashboards and commercial journeys designed to validate the offer, organize operations and scale with applied AI.', service_web_link: 'Explore SaaS development', service_mobile_kicker: 'Companion / operations', service_mobile_title: 'Android &amp; iOS apps with AI', service_mobile_desc: 'Cross-platform apps for customers and field teams, connected to your product and assisted by AI where the journey needs speed.', service_mobile_link: 'Explore mobile app development', service_ai_kicker: 'Applied intelligence', service_ai_title: 'Applied AI', service_ai_desc: 'Automation, assistants, intelligent search and data-driven decisions — AI where it creates real value.', service_ai_link: 'Talk about applied AI', service_arch_kicker: 'Built to grow', service_arch_title: 'Architecture &amp; APIs', service_arch_desc: 'Backend, integrations, observability and performance for products that need to be reliable today and tomorrow.', service_arch_link: 'Talk about architecture and APIs', service_advisory_kicker: 'Senior perspective', service_advisory_title: 'Advisory &amp; technical leadership', service_advisory_desc: 'Senior perspective to take decisions out of the opinion zone: discovery, roadmap, prioritization, architecture review and hands-on direction.', service_advisory_link_page: 'Explore advisory and technical leadership', service_advisory_link: 'Talk about a challenge',
        method_kicker: 'How the work happens', method_title: 'Clarity to decide. Momentum to deliver.', method_intro: 'Technology is the instrument. First comes context, then the right decision, then building and continuous evolution.', method_cta: 'Start with discovery', method_visual_caption: 'end-to-end view', method_visual_principle_1: 'problem understood', method_visual_principle_2: 'decision recorded', method_visual_principle_3: 'product evolving', method_1_title: 'Understand', method_1_desc: 'I map the goal, users, constraints and what really needs to change.', method_1_tag: 'context', method_2_title: 'Design', method_2_desc: 'I turn the problem into scope, architecture and priorities that fit the business moment.', method_2_tag: 'direction', method_3_title: 'Build', method_3_desc: 'I develop with visible deliveries, recorded decisions and quality from the first version.', method_3_tag: 'delivery', method_4_title: 'Evolve', method_4_desc: 'I stay close after launch, read the signals and adjust the product so it keeps creating value.', method_4_tag: 'evolution',
        cases_kicker: 'Proof for a commercial decision', cases_title: 'Real products, critical journeys and pages that make the next step obvious.', cases_intro: 'See how SaaS, mobile and applied AI enter healthcare, telecom, franchise and startup contexts without losing business clarity.', cases_note_label: 'CURATED SELECTION', cases_note_text: 'Product, operations and conversion in the same delivery.', case_footer_note: 'from context to delivery', case_open_project: 'View landing page', case_samu_tag: 'HEALTHCARE · MOBILE', case_samu_outcome: 'Critical real-time operation', case_true_client: 'Project delivered for TRUE Tecnologia para Vida', case_samu_title: 'SAMU 192', case_samu_desc: 'A critical journey where geolocation, real-time behavior and simplicity need to work when every second matters. The product connects calls, location and care in a simple experience for people who need to act fast.', case_unimed_tag: 'HEALTHCARE · APP', case_unimed_outcome: 'Digital beneficiary journey', case_unimed_title: 'Unimed', case_unimed_desc: 'A digital beneficiary experience bringing coverage, authorizations and services together. A clearer journey to access information, services and next steps without friction.', case_banana_tag: 'STARTUP · AI', case_banana_outcome: 'Intelligent match for decisions', case_banana_title: 'Banana Startups', case_banana_desc: 'Intelligent matching between startups and investors: from hypothesis to MVP with room to learn and grow. The experience brings discovery, criteria and connection into one flow.', case_native_tag: 'SAAS · WEB', case_native_outcome: 'SaaS with a conversion narrative', case_native_title: 'Native IP', case_native_desc: 'Technical communication translated into commercial benefits for an ISP SaaS platform. The page turns a complex offer into a more direct commercial conversation.', case_streetme_tag: 'FRANCHISE · WEB', case_streetme_outcome: 'Acquisition for brand expansion', case_streetme_title: 'StreetMe Cafés', case_streetme_desc: 'Franchisee acquisition landing page with business storytelling, market proof and a clear path to the lead. Every block was designed to reduce doubt and speed up the next contact.', case_turquesa_tag: 'FRANCHISE · BEAUTY', case_turquesa_outcome: 'Acquisition for a growing network', case_turquesa_title: 'Turquesa Bem-Estar', case_turquesa_desc: 'A commercial experience presenting the franchise model, organizing key indicators and guiding entrepreneurs toward the next step with more confidence.', case_empreender_tag: 'EVENT · WEB', case_empreender_outcome: 'Digital experience for connection and sales', case_empreender_title: 'Empreender 40+', case_empreender_desc: 'Landing page for the Empreender 40+ Summit, organizing the proposition, speakers, schedule and ticket conversion into a clear event journey.', case_empreender_link: 'View project site',
        fit_kicker: 'Maybe the next project is yours', fit_title: 'If there is an opportunity, a bottleneck or an important idea, we can start.', fit_1: 'You need to validate an MVP without building an entire team.', fit_2: 'Your product grew and the architecture is starting to send the bill.', fit_3: 'The company wants to apply AI but is not sure where it makes sense.', fit_4: 'You need someone senior to connect decisions and execution.',
        contact_kicker: 'Contact', contact_title: 'Let’s turn an opportunity into a product.', contact_intro: 'Tell me what you want to sell, run or simplify. In a focused conversation, we will frame the first slice and the best path for SaaS, mobile and AI.', contact_aside_label: 'WHAT YOU GET', contact_aside_text: 'Clarity on priority, initial scope and next steps — without committing to a generic package.', contact_context_label: 'WHAT YOU CAN SEND', contact_context_1: 'A SaaS to validate or take into operation', contact_context_2: 'An app for customers, teams or field work', contact_context_3: 'An AI opportunity with a clear gain', contact_availability: 'You speak directly with someone who connects product, architecture and execution — from first slice to evolution.', contact_whatsapp: '+55 (51) 98012-0387', contact_email: 'ggbarcelos@gmail.com', contact_form_kicker: 'QUICK BRIEF', contact_form_title: 'Let’s start with the right context.', contact_linkedin: 'LinkedIn / glauber-gomes-barcelos', contact_name_label: 'Your name', contact_name_ph: 'What should I call you?', contact_wa_label: 'WhatsApp', contact_wa_ph: '+55 (51) 98012-0387', contact_msg_label: 'What do you want to build?', contact_msg_ph: 'It can be an idea, a problem or an ongoing project…', contact_submit: '<span>Send context</span><i class="fas fa-arrow-right" aria-hidden="true"></i>', footer_copy: '© 2026 Glauber Barcelos. Software engineering for products that move forward.', wa_float_label: 'Talk on WhatsApp', err_name: 'Please enter your full name.', err_contact: 'Please enter a valid WhatsApp number.', err_message: 'Tell me a little more about what you want to build.', err_fields: 'Please review the highlighted fields and try again.', sending: 'Sending message...', sent_ok: 'Message sent! I will reach out on WhatsApp shortly. 🚀', send_error: 'Unable to send right now. Please try WhatsApp instead.', send_btn_original: '<span>Send context</span><i class="fas fa-arrow-right" aria-hidden="true"></i>',
    }
};

function detectLang() {
    const saved = localStorage.getItem('gb_lang');
    if (saved) return saved;
    const nav = (navigator.language || navigator.userLanguage || 'pt').toLowerCase();
    return nav.startsWith('pt') ? 'pt' : 'en';
}

function applyLang(lang) {
    const t = translations[lang];
    if (!t) return;
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : 'en';
    localStorage.setItem('gb_lang', lang);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (!Object.prototype.hasOwnProperty.call(t, key)) return;
        const attr = el.getAttribute('data-i18n-attr');
        if (attr) el.setAttribute(attr, t[key]);
        else el.innerHTML = t[key];
    });
    const btn = document.getElementById('langToggle');
    if (btn) btn.innerHTML = t.nav_lang_btn;
}

function toggleLang() {
    const current = localStorage.getItem('gb_lang') || detectLang();
    applyLang(current === 'pt' ? 'en' : 'pt');
}

window.__i18n = { detectLang, applyLang, toggleLang, translations };
